[tools]

# -- [[ Runtimes ]]
node = '20'
python = '3.10.12'
rust = 'latest'
go = 'latest'
bun = 'latest'
ruby = 'latest'

# -- [[ Tools ]]
neovim = 'latest'
tmux = "latest"
television = "latest"
"go:github.com/joshmedeski/sesh/v2" = { version = "latest" }
uv = 'latest'
gh = "latest"
kubectl = "latest"
bat = 'latest'
eza = 'latest'
aws-cli = 'latest'
fzf = 'latest'
jq = "latest"
yq = "latest"
ast-grep = "latest"
lazygit = "latest"
opencode = "latest"
pandoc = "latest"
delta = "latest"
gum = "latest"
glow = "latest"
duf = "latest"
"github:zk-org/zk" = "latest"
gemini-cli = "latest"
"asdf:mise-plugins/mise-sqlite" = "latest"
"pipx:jc" = "latest"
"pnpm" = "latest"
"viteplus" = "latest"
gcloud = "latest"
"cargo:https://github.com/googleworkspace/cli" = "latest"
"pipx:markitdown" = { version = "latest", extras = "all"}
typst = "latest"

[tasks."github:repositories"]
description = 'Search and open Github repositories'
run = 'gh s --user=shakedlokits | xargs -I {} open --url {}'

[tasks."github:pull-requests"]
description = "Search and open GitHub PRs"
run = "gh search prs --author=@me --state=open | column -t -s $'\t' | fzf --wrap | awk '{print $1, $2}' | xargs -L1 sh -c 'gh pr view --web --repo \"$1\" \"$2\"' _"

[tasks."git:checkout-latest-branches"]
description = "List and checkout the latest git branches"
run = "git for-each-ref --sort=-committerdate refs/heads/ --format='%(committerdate:relative)%09%(refname:short)' | fzf --wrap | awk -F'\t' '{print $2}' | xargs -I {} git checkout {}"

[tasks."code-complexity"]
description = 'Run a complexity test on a directory'
run = 'mise x go:github.com/boyter/scc/v3@latest -- scc --by-file --not-match ".*(Test|test).*" --format wide --percent --wide --sort "complexity"'
dir = "{{cwd}}"

